---
- name: provisions OpenNMS
  hosts: all
  become: true
  vars:
  roles:
    - role: mrlesmithjr.ntp
    - role: mrlesmithjr.postgresql
    - role: mrlesmithjr.postfix
    - role: pvanheus.java
    - role: mrlesmithjr.opennms
    - role: galaxyproject.nginx
  tasks:
    - name: set HTTPS config for opennms
      ansible.builtin.copy:
       dest: /etc/opennms/opennms.properties.d/jetty-https.properties
       content: opennms.web.base-url = https://%x%c/ 
       
