---
galaxy_info:
  author: Larry Smith Jr.
  description: An Ansible role to install/configure Postgresql
  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: Debian
      versions:
        - jessie
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - trusty
        - xenial

  galaxy_tags:
    - sql
dependencies: []
