---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu1404
    image: ubuntu:14.04
    dockerfile: ./../shared/Dockerfile.j2
  - name: ubuntu1604
    image: ubuntu:16.04
    dockerfile: ./../shared/Dockerfile.j2
  - name: ubuntu1804
    image: ubuntu:18.04
    dockerfile: ./../shared/Dockerfile.j2
provisioner:
  name: ansible
  env:
    PSQL_VERSION: ${PSQL_VERSION:-9.6}
  # options:
  #   vvv: true
  playbooks:
    converge: ./../shared/playbook.yml
  lint:
    name: ansible-lint
    options:
      x: ["503"]
verifier:
  name: testinfra
  directory: ./../shared/tests
  lint:
    name: flake8
